# Generated by Django 2.2.5 on 2021-02-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=100)),
                ('tz', models.CharField(max_length=100)),
                ('start_activity', models.CharField(max_length=100)),
                ('end_activity', models.CharField(max_length=100)),
            ],
        ),
    ]
